[package]
name = "orbtk"
version = "0.4.0-alpha1-alpha4"
authors = [
    "Florian Blasius <flovanpt@posteo.de>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = "The Orbital Widget Toolkit is a cross-platform (G)UI toolkit."
documentation = "https://docs.rs/orbtk"
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
]
edition = "2018"

[lib]
name = "orbtk"
path = "src/lib.rs"

[dependencies]
orbtk_base = { version = "0.4.0-alpha1", path = "../orbtk_base" }
orbtk_orbclient = { version = "0.4.0-alpha1", path = "../orbtk_orbclient", optional = true }
orbtk_shell = { version = "0.4.0-alpha1", path = "../orbtk_shell" }
orbtk_tinyskia = { version = "0.4.0-alpha1", path = "../orbtk_tinyskia" }
orbtk_widgets = { version = "0.4.0-alpha1", path = "../orbtk_widgets" }

[features]
default = ["orbtk_orbclient"]
# immediate mode (blank shell no App)
im = []